# Generated by Django 5.2.5 on 2025-08-12 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verified',
        ),
    ]
